language: python
python:
    - "2.7"
    - "3.2"
install:
    - pip install -r requirements.txt
script:
    - python "src/Opdracht 1/Opdracht1.py"
    - python "src/Opdracht 2/Opdracht2.py"
    - python "src/Opdracht 3/Opdracht3.py"
notifications:
  email: false